-- auto Generated on 2019-01-22 14:05:19 
-- DROP TABLE IF EXISTS `operate_biz`; 
CREATE TABLE operate_biz(
    `oper_id` BIGINT(30) NOT NULL DEFAULT 0 COMMENT 'operId',
    `oper_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '操作简称 比如 递延',
    `type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '类型',
    `project` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '项目归属',
    `desc` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'desc',
    `label` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '标签',
    `env_type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '环境类型',
    `url` VARCHAR(100) NOT NULL DEFAULT '' COMMENT 'url',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    PRIMARY KEY (`oper_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'operate_biz';
